services:
  - type: web
    name: controledegastos
    runtime: docker
    repo: https://github.com/GuilhermeSoares2005/Controle-de-Gastos
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: controlegastos-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: controlegastos-db
    databaseName: controlegastos
    plan: starter

