services:
  - type: web
    name: controledegastos
    runtime: docker
    repo: https://github.com/GuilhermeSoares2005/Controle-de-Gastos
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: controlegastos-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: controlegastos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: controlegastos-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: controlegastos-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: controlegastos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: controlegastos-db
          property: password
    healthCheckPath: /

databases:
  - name: controlegastos-db
    databaseName: controlegastos
    plan: starter

